spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:maindb;
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  shell:
    interactive:
      enabled: false
  data:
    rest:
      base-path: /datarest
  jmx:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  endpoint:
    health:
      show-components: always
      show-details: always
    metrics:
      enabled: true
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true
  metrics:
    export:
      simple:
        enabled: true
logging:
  file:
    name: application.log
    path: ./logs