spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always

  datasource:
#    url: jdbc:h2:mem:maindb; MODE=LEGACY
    url: jdbc:h2:mem:maindb;
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  shell:
    interactive:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true