spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      port: 27017
      database: book_lib
      host: localhost

  shell:
    interactive:
      enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local